site_name:           Nemo.jl
repo_url:            https://github.com/Nemocas/Nemo.jl
site_description:    Nemo
site_author:         William Hart

theme:               readthedocs

pages:
- Getting Started:              index.md
- About Nemo:                   about.md
- Types in Nemo:                types.md
- Parent object constructors:   constructors.md
- Univariate polynomials:       polynomial.md
- Series:                       series.md
- Residue rings:                residue.md             
- Fraction fields:              fraction.md
- Matrices:                     matrix.md
- Integers:                     integer.md
- Rationals:                    rational.md
- Finite fields:                finitefield.md
- Finite field embeddings:      ff_embedding.md
- P-adic fields:                padic.md
- Q-adic fields:                qadic.md
- Real balls:                   arb.md
- Complex boxes:                acb.md
- Number fields:                numberfield.md
- Factorization:                factor.md

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

docs_dir: 'build'

extra_javascript: ['mathjaxhelper.js', 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-AMS_HTML']
