name: Create documentation

on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
  workflow_dispatch:

jobs:
  create-documentation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.1.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.4'
      - uses: julia-actions/julia-buildpkg@latest
      - name: "Add Documenter package"
        run: julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                                  Pkg.instantiate()'
      - name: "Build and deploy documentation"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia --project=docs/ docs/make.jl
